---
options:
  filter:
    type: ["container"]
  # container: ["some_container_name"]
  # image: ["some_image_name"]
  # event: ["start", "stop", "die", "destroy"]
  exclude_strings: ["Action=exec_start", "Action=exec_die", "Action=exec_create"]
  log_level: debug
  server_tag: My Server

reporter:
  pushover:
    enabled: true
    api_token: xyz
    user_key: abc
  gotify:
    enabled: true
    url: http://gotify.lan
    token: xyz
  mail:
    enabled: true
    from: your.username@provider.com
    to: recipient@provider.com
    user: SMTP Username
    password: SMTP Password
    port: 587
    host: SMTP Host
  mattermost:
    enabled: true
    url: http://mattermost.lan
    channel: Docker Event Channel
    user: Docker Event Bot

notifications:
  - name: "Alert me when watchtower/.* based container restarts"
    event:
      "Action": ["(start|stop)"]
      "Actor.Attributes.image": ["watchtower/.*"]
    notify:
      - pushover
      - mail
      - gotify
  - name: "Alert me when unifi/.* based container dies with exitCode 1"
    event:
      "Action": ["(die|destroy)"]
      "Actor.Attributes.image": ["unifi/.*"]
      "Actor.Attributes.exitCode": ["1"]
    notify:
      - pushover
      - mattermost

  - name: "Alert only on gotify when container dies with exitCode 0"
    event:
      "Action": ["(die|destroy)"]
      "Actor.Attributes.image": ["pihole/.*"]
      "Actor.Attributes.exitCode": ["0"]
    notify:
      - gotify
