name: Build and publish Docker image

on:
  workflow_dispatch:
  release:
    types: [published]
  pull_request:
  push:
    branches:
    - development

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}

permissions:
  contents: read

jobs:
  build-prepare:
    runs-on: ubuntu-24.04
    outputs:
      REGISTRY_IMAGE: ${{ env.REGISTRY_IMAGE }}
      GIT_TAG: ${{ env.GIT_TAG }}
      GIT_BRANCH: ${{ env.GIT_BRANCH }}
      GIT_VERSION: ${{ env.GIT_VERSION }}
      GIT_COMMIT: ${{ env.GIT_COMMIT }}
      GIT_DATE: ${{ env.GIT_DATE }}
    steps:
      # FIXME: can't use env object in reusable workflow inputs: https://github.com/orgs/community/discussions/26671
      - run: echo "Exposing env vars for reusable workflow"

      - name: Checkout Code
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: "Calculate required variables"
        id: variables
        run: |
          GIT_TAG=${{ github.event.release.tag_name }}
          # If GIT_TAG is set then GIT BRANCH should be "main", else get it from the branch name
          GIT_BRANCH=$([ -n "${GIT_TAG}" ] && echo "main" || git rev-parse --abbrev-ref HEAD)
          GIT_VERSION=$(git --no-pager describe --tags --always --abbrev=8 --dirty)
          GIT_COMMIT=$(git --no-pager describe --always --abbrev=8 --dirty)
          GIT_DATE=$(git --no-pager show --date=short --format=%at --name-only | head -n 1)
          echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GIT_BRANCH}" >> $GITHUB_ENV
          echo "GIT_VERSION=${GIT_VERSION}" >> $GITHUB_ENV
          echo "GIT_COMMIT=${GIT_COMMIT}" >> $GITHUB_ENV
          echo "GIT_DATE=${GIT_DATE}" >> $GITHUB_ENV
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1.6.0
    permissions:
      contents: read
      packages: write # required to push to GHCR
      id-token: write # for signing attestation(s) with GitHub OIDC Token
    needs:
      - build-prepare
    with:
      runner: auto
      distribute: true
      setup-qemu: true
      output: image
      cache: true
      cache-scope: build
      push: ${{ github.actor != 'dependabot[bot]' && ( github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'push' || github.event_name == 'release' ) }}
      meta-images: ${{ needs.build-prepare.outputs.REGISTRY_IMAGE }}
      meta-flavor: latest=${{ startsWith(github.ref, 'refs/tags/') }}
      meta-tags: |
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
        type=sha,enable=${{ github.event_name == 'workflow_dispatch' }}
        type=ref,event=pr
        type=ref,event=branch
      platforms: linux/amd64,linux/arm64, linux/arm/v6, linux/arm/v7, linux/386
      # FIXME: GHCR does not support the referrers API and spams the registry with sha-tagged images when cosigned: https://github.com/docker/github-builder/issues/109
      sign: false
      build-args: |
        GIT_TAG=${{ needs.build-prepare.outputs.GIT_TAG }}
        GIT_BRANCH=${{ needs.build-prepare.outputs.GIT_BRANCH }}
        GIT_VERSION=${{ needs.build-prepare.outputs.GIT_VERSION }}
        GIT_COMMIT=${{ needs.build-prepare.outputs.GIT_COMMIT }}
        GIT_DATE=${{ needs.build-prepare.outputs.GIT_DATE }}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
